// tom-weatherhead/thaw-lexical-analyzer/src/lexical-states.ts

export enum LexicalState {
	tokenNone = 1,
	tokenIntLit,
	tokenFltLit,
	tokenStrLit,
	tokenStrLit2,
	tokenIdent,
	tokenBoolIdent,
	tokenSkolemIdent,
	tokenVariable,
	tokenMult,
	tokenDiv,
	tokenPlus,
	tokenMinus,
	tokenEqual,
	tokenNotEqual,
	tokenLess,
	tokenLessEqual,
	tokenGreater,
	tokenGreaterEqual,
	tokenSemicolon,
	tokenComma,
	token2OrBar,
	token2Ampersand,
	tokenLeftBracket,
	tokenRightBracket,
	tokenAssign,
	tokenArrow,
	tokenExclamation,
	tokenApostrophe,
	tokenOctothorpe,
	tokenDollar,
	tokenDot,
	tokenLeftSquareBracket,
	tokenRightSquareBracket,
	tokenOrBar,
	tokenColon,
	tokenLeftCurlyBrace,
	tokenRightCurlyBrace,
	tokenQuoteKeyword,
	tokenQuestionMinus,
	tokenColonMinus,
	tokenEqualLessThan,
	tokenBackslashPlus,
	tokenBackslashEqual,
	tokenEqualEqual,
	tokenBackslashEqualEqual,
	tokenEqualColonEqual,
	tokenEqualBackslashEqual,
	tokenMinusMinusGreaterThan,
	tokenEqualDotDot,
	tokenCaret,
	tokenEOF,

	// Non-accept (intermediate) states
	stateStart,
	stateError,
	stateStrLitOpen,
	stateStrLit2Open,
	stateIntLitDot,
	stateQuestion,
	stateAmpersand,
	stateAt,
	stateDollar,
	stateBackslash,
	stateEqualColon,
	stateEqualBackslash,
	stateMinusMinus,
	stateEqualDot
}

// T_EOF_Error,            // End of file (one or more errors detected)
// T_2DOT,			    /* .. */
// T_POWER,			    /* ** */
